"""M9 CAT/EPT entropic time, relational clocks, gravity, and continuum dynamics.

Current integrated lineage reaches M9.124. The new layer distinguishes three
complementary aspects of time:

* Page-Wootters time: relational ordering by conditioning on a clock subsystem;
* modular/thermal time: reversible state-dependent flow generated by K = -log rho;
* entropic time: irreversible accumulation from dissipation or relaxation.

The three roles have pairwise formal bridges but are not registered as one
identical physical clock. A common carrier, parameter calibration, full
constraint-to-conditioning theorem, and held-out evidence remain open.
"""

CURRENT_MILESTONE = "M9.124"
CURRENT_REGISTRATION_SCHEMA = "openwave.model-registration.v27"
CURRENT_CONFORMANCE_SCHEMA = "openwave.m9.models-conformance.v22"
