"""M9.132a: coupled CAT/EPT matter, geometry, and entropic-time evolution.

The reduced periodic carrier evolves one complex matter field, a self-consistent
Newtonian geometry potential, and an accumulated entropic clock in one loop.
The imaginary-action contribution is implemented as norm-preserving energy
relaxation generated by ``(H - <H>)`` rather than as an independently normalized
post-processing curve.

This is a dimensionless reduced simulation, not a complete relativistic field
theory or a production Einstein--matter solver.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from functools import lru_cache
import json
import math
from typing import Any, Mapping

import numpy as np

Array = np.ndarray


@dataclass(frozen=True)
class CoupledCATEPTConfig:
    points: int = 96
    half_width: float = 12.0
    time_step: float = 2.0e-4
    steps: int = 1200
    sample_stride: int = 20
    mass: float = 1.0
    hbar: float = 1.0
    self_coupling: float = 0.45
    gravity_coupling: float = 0.12
    geometry_relaxation: float = 2.0
    kinetic_source_weight: float = 0.08
    dissipation: float = 0.035
    dissipation_density_feedback: float = 0.5

    def __post_init__(self) -> None:
        if self.points < 32 or self.points % 2:
            raise ValueError("an even periodic grid with at least 32 points is required")
        if self.steps < 10 or self.sample_stride < 1:
            raise ValueError("substantive evolution and positive sampling are required")
        if min(
            self.half_width,
            self.time_step,
            self.mass,
            self.hbar,
            self.geometry_relaxation,
        ) <= 0.0:
            raise ValueError("positive geometric and evolution controls are required")
        if min(
            self.self_coupling,
            self.gravity_coupling,
            self.kinetic_source_weight,
            self.dissipation,
            self.dissipation_density_feedback,
        ) < 0.0:
            raise ValueError("nonnegative CAT/EPT couplings are required")


@dataclass
class CoupledCATEPTState:
    psi: Array
    potential: Array
    entropic_time: float = 0.0


def periodic_grid(cfg: CoupledCATEPTConfig) -> tuple[Array, Array, float]:
    length = 2.0 * cfg.half_width
    spacing = length / cfg.points
    x = -cfg.half_width + spacing * np.arange(cfg.points, dtype=np.float64)
    wave = 2.0 * math.pi * np.fft.fftfreq(cfg.points, d=spacing)
    return x, wave, spacing


def normalize(psi: Array, spacing: float) -> Array:
    norm = math.sqrt(spacing * float(np.sum(np.abs(psi) ** 2)))
    if not math.isfinite(norm) or norm <= 0.0:
        raise ValueError("positive finite matter norm required")
    return np.asarray(psi / norm, dtype=np.complex128)


def derivative(values: Array, wave: Array) -> Array:
    return np.asarray(np.fft.ifft(1.0j * wave * np.fft.fft(values)), dtype=np.complex128)


def laplacian(values: Array, wave: Array) -> Array:
    return np.asarray(np.fft.ifft(-(wave**2) * np.fft.fft(values)), dtype=np.complex128)


def matter_density(psi: Array) -> Array:
    return np.asarray(np.abs(psi) ** 2, dtype=np.float64)


def kinetic_density(psi: Array, wave: Array, cfg: CoupledCATEPTConfig) -> Array:
    grad = derivative(psi, wave)
    return np.asarray(
        (cfg.hbar**2 / (2.0 * cfg.mass)) * np.abs(grad) ** 2,
        dtype=np.float64,
    )


def geometry_source(psi: Array, wave: Array, cfg: CoupledCATEPTConfig) -> Array:
    rho = matter_density(psi)
    kinetic = kinetic_density(psi, wave, cfg)
    source = rho + cfg.kinetic_source_weight * kinetic
    return np.asarray(source - np.mean(source), dtype=np.float64)


def target_potential(psi: Array, wave: Array, cfg: CoupledCATEPTConfig) -> Array:
    """Solve ``-Delta phi = 4 pi G (rho + eta T - mean)`` on active modes."""
    source_hat = np.fft.fft(geometry_source(psi, wave, cfg))
    target_hat = np.zeros_like(source_hat, dtype=np.complex128)
    active = wave != 0.0
    target_hat[active] = 4.0 * math.pi * cfg.gravity_coupling * source_hat[active] / (
        wave[active] ** 2
    )
    return np.asarray(np.fft.ifft(target_hat).real, dtype=np.float64)


def hamiltonian_action(
    psi: Array,
    potential: Array,
    wave: Array,
    cfg: CoupledCATEPTConfig,
) -> Array:
    kinetic = -(cfg.hbar**2 / (2.0 * cfg.mass)) * laplacian(psi, wave)
    rho = matter_density(psi)
    nonlinear = (cfg.self_coupling * rho + cfg.mass * potential) * psi
    return np.asarray(kinetic + nonlinear, dtype=np.complex128)


def expectation(psi: Array, operator_psi: Array, spacing: float) -> float:
    return float(np.real(spacing * np.vdot(psi, operator_psi)))


def energy_variance(
    psi: Array,
    potential: Array,
    wave: Array,
    spacing: float,
    cfg: CoupledCATEPTConfig,
) -> tuple[float, float]:
    h_psi = hamiltonian_action(psi, potential, wave, cfg)
    mean_energy = expectation(psi, h_psi, spacing)
    centered = h_psi - mean_energy * psi
    variance = spacing * float(np.sum(np.abs(centered) ** 2))
    return mean_energy, max(variance, 0.0)


def effective_dissipation(psi: Array, cfg: CoupledCATEPTConfig) -> Array:
    rho = matter_density(psi)
    contrast = rho / max(float(np.mean(rho)), 1.0e-300)
    return np.asarray(
        cfg.dissipation * (1.0 + cfg.dissipation_density_feedback * contrast),
        dtype=np.float64,
    )


def coupled_rhs(
    state: CoupledCATEPTState,
    wave: Array,
    spacing: float,
    cfg: CoupledCATEPTConfig,
) -> tuple[Array, Array, float, dict[str, float]]:
    h_psi = hamiltonian_action(state.psi, state.potential, wave, cfg)
    mean_energy = expectation(state.psi, h_psi, spacing)
    centered = h_psi - mean_energy * state.psi
    gamma = effective_dissipation(state.psi, cfg)

    unitary_rhs = -1.0j * h_psi / cfg.hbar
    irreversible_rhs = -(gamma / cfg.hbar) * centered
    psi_rhs = np.asarray(unitary_rhs + irreversible_rhs, dtype=np.complex128)

    target = target_potential(state.psi, wave, cfg)
    potential_rhs = cfg.geometry_relaxation * (target - state.potential)

    local_production = gamma * np.abs(centered) ** 2 / (cfg.hbar**2)
    entropic_rate = spacing * float(np.sum(local_production))
    diagnostics = {
        "mean_energy": mean_energy,
        "energy_variance": spacing * float(np.sum(np.abs(centered) ** 2)),
        "entropic_rate": max(entropic_rate, 0.0),
        "geometry_target_error": math.sqrt(
            spacing * float(np.sum((target - state.potential) ** 2))
        ),
        "mean_effective_dissipation": float(np.mean(gamma)),
    }
    return psi_rhs, np.asarray(potential_rhs, dtype=np.float64), max(entropic_rate, 0.0), diagnostics


def step(
    state: CoupledCATEPTState,
    wave: Array,
    spacing: float,
    cfg: CoupledCATEPTConfig,
) -> tuple[CoupledCATEPTState, dict[str, float]]:
    psi_rhs, potential_rhs, entropic_rate, diagnostics = coupled_rhs(
        state, wave, spacing, cfg
    )
    next_psi = normalize(state.psi + cfg.time_step * psi_rhs, spacing)
    next_potential = np.asarray(
        state.potential + cfg.time_step * potential_rhs,
        dtype=np.float64,
    )
    next_potential -= float(np.mean(next_potential))
    next_state = CoupledCATEPTState(
        psi=next_psi,
        potential=next_potential,
        entropic_time=state.entropic_time + cfg.time_step * entropic_rate,
    )
    return next_state, diagnostics


def initialize_state(cfg: CoupledCATEPTConfig) -> CoupledCATEPTState:
    x, wave, spacing = periodic_grid(cfg)
    left = np.exp(-((x + 2.0) / 1.35) ** 2) * np.exp(0.7j * x)
    right = 0.72 * np.exp(-((x - 2.4) / 1.0) ** 2) * np.exp(-0.45j * x + 0.4j)
    psi = normalize(left + right, spacing)
    potential = target_potential(psi, wave, cfg)
    return CoupledCATEPTState(psi=psi, potential=potential, entropic_time=0.0)


def state_diagnostics(
    state: CoupledCATEPTState,
    wave: Array,
    spacing: float,
    cfg: CoupledCATEPTConfig,
) -> dict[str, float]:
    rho = matter_density(state.psi)
    grad = derivative(state.psi, wave)
    mean_energy, variance = energy_variance(
        state.psi, state.potential, wave, spacing, cfg
    )
    target = target_potential(state.psi, wave, cfg)
    coherence = abs(spacing * np.sum(state.psi * np.roll(np.conj(state.psi), cfg.points // 4)))
    return {
        "norm": spacing * float(np.sum(rho)),
        "mean_energy": mean_energy,
        "energy_variance": variance,
        "entropic_time": state.entropic_time,
        "density_peak": float(np.max(rho)),
        "density_variance": float(np.var(rho)),
        "coherence_quarter_period": float(coherence),
        "potential_l2": math.sqrt(spacing * float(np.sum(state.potential**2))),
        "geometry_target_error": math.sqrt(
            spacing * float(np.sum((target - state.potential) ** 2))
        ),
        "kinetic_l2": math.sqrt(spacing * float(np.sum(np.abs(grad) ** 2))),
    }


def run_with_config(cfg: CoupledCATEPTConfig) -> dict[str, Any]:
    _, wave, spacing = periodic_grid(cfg)
    state = initialize_state(cfg)
    records: list[dict[str, float]] = []
    minimum_entropic_increment = float("inf")

    for index in range(cfg.steps + 1):
        if index % cfg.sample_stride == 0 or index == cfg.steps:
            records.append({"time": index * cfg.time_step, **state_diagnostics(state, wave, spacing, cfg)})
        if index == cfg.steps:
            break
        previous_entropic = state.entropic_time
        state, _ = step(state, wave, spacing, cfg)
        minimum_entropic_increment = min(
            minimum_entropic_increment,
            state.entropic_time - previous_entropic,
        )

    acceptance = {
        "matter_norm_is_preserved": max(abs(row["norm"] - 1.0) for row in records) <= 5.0e-12,
        "entropic_time_is_monotone": minimum_entropic_increment >= -1.0e-14,
        "entropic_time_advances": records[-1]["entropic_time"] > records[0]["entropic_time"],
        "geometry_is_dynamical": any(
            abs(row["potential_l2"] - records[0]["potential_l2"]) > 1.0e-10
            for row in records[1:]
        ),
        "matter_distribution_is_dynamical": any(
            abs(row["density_peak"] - records[0]["density_peak"]) > 1.0e-8
            for row in records[1:]
        ),
        "feedback_error_is_finite": all(math.isfinite(row["geometry_target_error"]) for row in records),
        "all_diagnostics_are_finite": all(
            math.isfinite(value) for row in records for value in row.values()
        ),
    }
    payload = {
        "schema": "openwave.m9.coupled-cat-ept-evolution.v1",
        "task": "M9.132a",
        "config": asdict(cfg),
        "records": records,
        "acceptance": acceptance,
        "claim_boundary": {
            "reduced_periodic_carrier_is_complete_CAT_EPT": False,
            "scalar_potential_is_full_Einstein_geometry": False,
            "dimensionless_parameters_are_physical_calibration": False,
            "normalization_step_is_unitary_dynamics": False,
        },
    }
    return {
        **payload,
        "passed": all(acceptance.values()) and not any(payload["claim_boundary"].values()),
        "decision": {
            "matter_geometry_entropy_evolved_together": True,
            "complex_action_feedback_constructed": True,
            "complete_relativistic_CAT_EPT_constructed": False,
            "physical_calibration_complete": False,
        },
    }


@lru_cache(maxsize=1)
def run_coupled_cat_ept_evolution() -> dict[str, Any]:
    return run_with_config(CoupledCATEPTConfig())


def result_to_json(result: Mapping[str, Any]) -> str:
    return json.dumps(result, indent=2, sort_keys=True, default=float) + "\n"
