"""M9.117 formal authority for dynamical screen coarse graining.

The numerical M9.117 adapters reuse exact theorem surfaces from the live
``entropic-physlib-linear-full`` branch.  The contract pins the formal revision and
source blobs, maps each theorem family to one numerical role, and preserves the
boundary between a theorem-guided adapter and a theorem generated by the simulator.
"""
from __future__ import annotations

from functools import lru_cache
from hashlib import sha256
import json
from typing import Any, Mapping

from .formalization_m109_extension import (
    CURRENT_FORMAL_HEAD,
    FORMAL_BRANCH,
    FORMAL_REPOSITORY,
    PHYSLIB_ROOT_BLOB,
    canonical_payload as previous_payload,
    run_formalization_m109_extension,
)


FORMAL_SOURCES = (
    {
        "path": "Physlib/QFT/HamiltonianRenormalisation/DirectHamiltonianFlow.lean",
        "blob": "b75e77e371938663ac744b52efff2018f31d0925",
        "role": "Gaussian pullback, automatic covariance fixed point, and principal/image coupling limits",
        "declarations": (
            "Physlib.QFT.HamiltonianRenormalisation.gaussianWeyl_flow",
            "Physlib.QFT.HamiltonianRenormalisation.covariance_fixedPoint_automatic",
            "Physlib.QFT.HamiltonianRenormalisation.couplingFunction_tendsto_one",
            "Physlib.QFT.HamiltonianRenormalisation.couplingFunction_tendsto_zero",
        ),
    },
    {
        "path": "Physlib/QFT/HamiltonianRenormalisation/FreeFieldFlowConsistency.lean",
        "blob": "f4243a9a8fe6dbc38b1e5bb62111030c21885544",
        "role": "free-field damping cocycle and full principal/image covariance limits",
        "declarations": (
            "Physlib.QFT.HamiltonianRenormalisation.transferRatio_cocycle_exp",
            "Physlib.QFT.HamiltonianRenormalisation.imagePoleTerm_tendsto_zero",
            "Physlib.QFT.HamiltonianRenormalisation.principalPoleTerm_tendsto_continuum",
            "Physlib.QFT.HamiltonianRenormalisation.continuum_covariance_dictionary",
        ),
    },
    {
        "path": "Physlib/QFT/HamiltonianRenormalisation/FreeScalarCovarianceFlow.lean",
        "blob": "7d878d9658f0c7f191fdd9a02ec682757b1c9767",
        "role": "block-spin covariance recursion and hyperbolic fixed-point covariance",
        "declarations": (
            "Physlib.QFT.HamiltonianRenormalisation.covariance_flow_step",
            "Physlib.QFT.HamiltonianRenormalisation.fixedPoint_covariance_flow",
            "Physlib.QFT.HamiltonianRenormalisation.continuum_projection_match",
        ),
    },
    {
        "path": "Physlib/Mathematics/DimensionalScalingFunctorTower.lean",
        "blob": "67ad22e5fde07d7251159a4a960087724b45494d",
        "role": "identity, composition, and ratio laws for scale transitions",
        "declarations": (
            "Physlib.Mathematics.DimensionalScaling.scalingFactor_ratio",
            "Physlib.Mathematics.DimensionalScaling.scalingTransition_id",
            "Physlib.Mathematics.DimensionalScaling.scalingTransition_comp",
            "Physlib.Mathematics.DimensionalScaling.scalingTransition_dimLength",
        ),
    },
)

SCOPE = {
    "formal_block_flow_available": True,
    "formal_gaussian_fixed_point_available": True,
    "formal_scale_composition_available": True,
    "formal_theorems_derive_particle_mass_endpoint": False,
    "formal_free_field_fixed_point_is_interacting_CAT_EPT_fixed_point": False,
    "formal_scale_flow_is_physical_screen_calibration": False,
}


def _is_sha(value: object) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 40
        and all(character in "0123456789abcdef" for character in value.lower())
    )


def expected_source_blobs() -> dict[str, str]:
    return {str(row["path"]): str(row["blob"]) for row in FORMAL_SOURCES}


def canonical_payload() -> dict[str, Any]:
    return {
        "schema": "openwave.m9.formalization-m117-extension.v1",
        "previous_authority": previous_payload(),
        "formal_repository": {
            "name": FORMAL_REPOSITORY,
            "branch": FORMAL_BRANCH,
            "current_head": CURRENT_FORMAL_HEAD,
            "physlib_root_blob": PHYSLIB_ROOT_BLOB,
        },
        "sources": [dict(row) for row in FORMAL_SOURCES],
        "scope": dict(SCOPE),
        "policy": {
            "theorem_guided_adapter_is_not_a_new_Lean_proof": True,
            "finite_block_flow_is_not_a_continuum_interacting_fixed_point": True,
            "mass_selected_endpoint_requires_separate_physics": True,
            "synthetic_screen_data_is_not_external_calibration": True,
        },
    }


def fingerprint(payload: Mapping[str, Any] | None = None) -> str:
    selected = canonical_payload() if payload is None else dict(payload)
    return sha256(
        json.dumps(selected, sort_keys=True, separators=(",", ":"), default=str).encode()
    ).hexdigest()


def validate_formalization_m117(
    *,
    observed_head: str | None = None,
    observed_root_blob: str | None = None,
    observed_source_blobs: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    head = CURRENT_FORMAL_HEAD if observed_head is None else observed_head
    root = PHYSLIB_ROOT_BLOB if observed_root_blob is None else observed_root_blob
    sources = expected_source_blobs() if observed_source_blobs is None else dict(observed_source_blobs)
    errors: list[str] = []
    if head != CURRENT_FORMAL_HEAD:
        errors.append("formal head drift detected")
    if root != PHYSLIB_ROOT_BLOB:
        errors.append("Physlib root drift detected")
    for path, blob in expected_source_blobs().items():
        if sources.get(path) != blob:
            errors.append(f"M9.117 formal source drift detected: {path}")
    return {"errors": errors, "passed": not errors}


@lru_cache(maxsize=1)
def run_formalization_m117_extension() -> dict[str, Any]:
    previous = run_formalization_m109_extension()
    validation = validate_formalization_m117()
    payload = canonical_payload()
    acceptance = {
        "previous_formal_authority_passes": bool(previous["passed"]),
        "formal_revision_and_root_are_exact": _is_sha(CURRENT_FORMAL_HEAD)
        and _is_sha(PHYSLIB_ROOT_BLOB),
        "four_scale_flow_sources_are_blob_pinned": len(FORMAL_SOURCES) == 4
        and all(_is_sha(row["blob"]) for row in FORMAL_SOURCES),
        "all_declared_theorem_families_are_nonempty": all(row["declarations"] for row in FORMAL_SOURCES),
        "source_validation_has_no_errors": bool(validation["passed"]),
        "mass_endpoint_and_interacting_fixed_point_remain_open": not SCOPE[
            "formal_theorems_derive_particle_mass_endpoint"
        ]
        and not SCOPE["formal_free_field_fixed_point_is_interacting_CAT_EPT_fixed_point"],
        "fingerprint_is_deterministic": fingerprint(payload) == fingerprint(payload),
    }
    return {
        **payload,
        "task": "M9.117-formal",
        "source_validation": validation,
        "fingerprint": fingerprint(payload),
        "acceptance": acceptance,
        "passed": all(acceptance.values()),
        "decision": {
            "Hamiltonian_renormalisation_authority_registered": True,
            "dimensional_scale_composition_authority_registered": True,
            "particle_mass_endpoint_derived": False,
            "physical_screen_calibration_complete": False,
        },
    }


def result_to_json(result: Mapping[str, Any]) -> str:
    return json.dumps(result, indent=2, sort_keys=True, default=str) + "\n"
