"""README/MODELS-aligned CAT/EPT conformance profile."""
from __future__ import annotations
from dataclasses import asdict,dataclass
from hashlib import sha256
import json
from typing import Any,Literal
Status=Literal["validated","partial","negative","not_yet"]
@dataclass(frozen=True)
class Criterion:
    key:str; domain:str; label:str; status:Status; evidence:tuple[str,...]; finding:str
CRITERIA:tuple[Criterion,...]=(
 Criterion("charge_quantization","particles","Charge quantization","partial",("openwave/xperiments/m9_cat_ept/topological_charge.py","openwave/xperiments/m9_cat_ept/research/findings/m9_26_method_note.md"),"Integer winding is field-derived and robust, but the sector is seeded and is not identified with elementary electric charge."),
 Criterion("electron_rest_energy","particles","Electron rest energy (mass)","partial",("openwave/xperiments/m9_cat_ept/scale_selection.py","openwave/xperiments/m9_cat_ept/research/findings/m9_27_method_note.md"),"A selected topological ansatz has an interior dimensionless scale minimum, but no physical mass or full CAT/EPT particle is established."),
 Criterion("de_broglie_clock","particles","de Broglie clock (Zitterbewegung)","partial",("openwave/xperiments/m9_cat_ept/intrinsic_clock_reduction.py","openwave/xperiments/m9_cat_ept/imaginary_action_backreaction.py","openwave/xperiments/m9_cat_ept/entropic_integrator.py"),"Reversible phase, entropic monotone, and geometry clock channels are separated; no Zitterbewegung or physical-time identity is accepted."),
 Criterion("particle_stability","particles","Particle stability (Derrick escape)","negative",("openwave/xperiments/m9_cat_ept/minimizer_3d.py","openwave/xperiments/m9_cat_ept/stability_campaign_3d.py","openwave/xperiments/m9_cat_ept/localized_state_search.py","openwave/xperiments/m9_cat_ept/spatial_3d_localization_decision.py","openwave/xperiments/m9_cat_ept/research/findings/m9_14_method_note.md","openwave/xperiments/m9_cat_ept/research/findings/m9_25_method_note.md","openwave/xperiments/m9_cat_ept/research/findings/m9_37_method_note.md","openwave/xperiments/m9_cat_ept/research/findings/m9_48_method_note.md"),"A trapped 3D minimizer survives a long-horizon perturbation campaign, but the untrapped control spreads, so no self-bound particle is accepted; the earlier bounded 3D candidate also fails its frozen localization gate."),
 Criterion("magnetic_moment_spin","particles","Magnetic moment and spin J","partial",("openwave/xperiments/m9_cat_ept/spin_magnetic_observables.py","openwave/xperiments/m9_cat_ept/research/findings/m9_29_method_note.md"),"Spin and a Pauli-current magnetic moment are field-integrated controls; no emergent electron g factor or stable particle is established."),
 Criterion("spin_half_statistics","particles","Spin-1/2 statistics (720-degree return)","partial",("openwave/xperiments/m9_cat_ept/spin_magnetic_observables.py","openwave/xperiments/m9_cat_ept/research/findings/m9_29_method_note.md"),"The spinor changes sign after 2pi and returns after 4pi, but exchange statistics are not established."),
 Criterion("antimatter_annihilation","particles","Antimatter and annihilation","partial",("openwave/xperiments/m9_cat_ept/capture_annihilation.py","openwave/xperiments/m9_cat_ept/research/findings/m9_31_method_note.md"),"A reduced opposite-sector model captures, annihilates, and transfers energy into radiation; full-PDE particle annihilation is not established."),
 Criterion("lepton_mass_spectrum","particles","Lepton mass spectrum (mu, tau)","negative",("openwave/xperiments/m9_cat_ept/lepton_hierarchy_audit.py","openwave/xperiments/m9_cat_ept/research/findings/m9_39_method_note.md"),"Current geometric and M9.27 effective-scale candidate laws fail predictive gates; exact three-parameter interpolation has zero residual degrees of freedom. No predictive hierarchy is selected."),
 Criterion("dark_matter","particles","Dark matter candidate","partial",("openwave/xperiments/m9_cat_ept/dark_sector_survey.py","openwave/xperiments/m9_cat_ept/research/findings/m9_45_method_note.md"),"An electrically neutral fixed-global-charge Gaussian survey finds a finite-charge bound candidate; full-PDE stability, abundance, and phenomenology remain open."),
 Criterion("quarks","particles","Quarks","partial",("openwave/xperiments/m9_cat_ept/quark_color_sector.py","openwave/xperiments/m9_cat_ept/research/findings/m9_46_method_note.md","openwave/xperiments/m9_cat_ept/research/zil/m9_46_quark_color.zc"),"Finite SU(3) color, singlet, Wilson-loop, fractional-charge, and CKM controls exist; dynamical QCD, emergent quarks, and physical hadron spectra remain open."),
 Criterion("baryons","particles","Baryons (p, n)","partial",("openwave/xperiments/m9_cat_ept/composite_graph.py","openwave/xperiments/m9_cat_ept/research/findings/m9_33_method_note.md"),"A charged-triplet graph binds and preserves ledgers, but no physical baryon or quark dynamics is established."),
 Criterion("mesons","particles","Mesons (pi, K)","partial",("openwave/xperiments/m9_cat_ept/composite_graph.py","openwave/xperiments/m9_cat_ept/research/findings/m9_33_method_note.md"),"A neutral-pair graph binds and preserves ledgers, but no physical meson or decay channel is established."),
 Criterion("electric_force","forces","Electric force (Coulomb 1/r)","partial",("openwave/xperiments/m9_cat_ept/two_body_forces.py","openwave/xperiments/m9_cat_ept/spatial_3d_maxwell_dirac.py","openwave/xperiments/m9_cat_ept/research/findings/m9_30_method_note.md"),"A regularized conservative kernel recovers the Coulomb-force asymptote, but no force between stable emergent charges is established."),
 Criterion("magnetic_force","forces","Magnetic force","partial",("openwave/xperiments/m9_cat_ept/two_body_forces.py","openwave/xperiments/m9_cat_ept/spin_magnetic_observables.py","openwave/xperiments/m9_cat_ept/spatial_3d_maxwell_dirac.py","openwave/xperiments/m9_cat_ept/research/findings/m9_30_method_note.md"),"A regularized dipole kernel recovers the r^-4 force asymptote; a particle-level CAT/EPT interaction is not established."),
 Criterion("strong_force","forces","Strong force / confinement","partial",("openwave/xperiments/m9_cat_ept/confinement_sector.py","openwave/xperiments/m9_cat_ept/research/findings/m9_40_method_note.md"),"A reduced Cornell/flux-tube control has linear potential growth, a constant-force asymptote, and a string-breaking ledger; QCD and dynamical color fields remain open."),
 Criterion("weak_force","forces","Weak force","partial",("openwave/xperiments/m9_cat_ept/weak_chiral_sector.py","openwave/xperiments/m9_cat_ept/research/findings/m9_41_method_note.md"),"A reduced left-selective flavor-mixing and decay ledger is qualified; electroweak gauge dynamics, W/Z fields, and physical rates remain open."),
 Criterion("gravity","forces","Gravity","partial",("openwave/xperiments/m9_cat_ept/geometry_backreaction.py","openwave/xperiments/m9_cat_ept/equivalence_principle.py","openwave/xperiments/m9_cat_ept/research/findings/m9_34_method_note.md","openwave/xperiments/m9_cat_ept/research/findings/m9_42_method_note.md"),"Weak-field metric, free-fall universality, redshift, tidal, and accelerated-frame controls exist; Einstein equations, tensor gravity, and physical coupling remain open."),
 Criterion("em_waves","waves","EM waves (Maxwell)","partial",("openwave/xperiments/m9_cat_ept/wave_reductions.py","openwave/xperiments/m9_cat_ept/spatial_3d_controls.py","openwave/xperiments/m9_cat_ept/research/findings/m9_43_method_note.md","openwave/xperiments/m9_cat_ept/research/data/m9_12_spatial_3d_controls_result.json"),"A transverse Maxwell reduction, energy/speed controls, and a massless scalar bridge are qualified; electromagnetism does not yet emerge from the full CAT/EPT system."),
 Criterion("klein_gordon","waves","Quantum wave equation (Klein-Gordon)","partial",("openwave/xperiments/m9_cat_ept/wave_reductions.py","openwave/xperiments/m9_cat_ept/research/findings/m9_43_method_note.md"),"A massive spectral Klein-Gordon reduction and dispersion control exist, with a regular massless Maxwell-component bridge; full native particle dynamics remain open."),
 Criterion("orbital_quantization","waves","Orbital quantization (atomic structure)","partial",("openwave/xperiments/m9_cat_ept/orbital_quantization.py","openwave/xperiments/m9_cat_ept/research/findings/m9_32_method_note.md"),"A converged Coulomb-like radial standing-wave ladder is resolved; atomic structure from the full CAT/EPT PDE is not established."),
 Criterion("thermal_field","thermal","Heat / thermal-field sector","partial",("openwave/xperiments/m9_cat_ept/thermal_field.py","openwave/xperiments/m9_cat_ept/research/findings/m9_44_method_note.md"),"A periodic heat equation conserves total heat, increases normalized thermal entropy, and satisfies diffusion-dissipation controls; microscopic CAT/EPT thermodynamics remain open."),
)
EXPECTED_VISIBLE_CRITERIA=21; DOCUMENTED_SUMMARY_TOTAL=21; MISSING_EXPLICIT_CRITERION=None

def validate_profile(criteria:tuple[Criterion,...]=CRITERIA)->dict[str,Any]:
    keys=[x.key for x in criteria]; labels=[x.label for x in criteria]
    if len(keys)!=len(set(keys)) or len(labels)!=len(set(labels)): raise ValueError("duplicate criterion")
    if len(criteria)!=EXPECTED_VISIBLE_CRITERIA: raise ValueError("profile must cover 21 explicit rows")
    if any(x.status!="not_yet" and not x.evidence for x in criteria): raise ValueError("non-planned status lacks evidence")
    domains={d:sum(x.domain==d for x in criteria) for d in ("particles","forces","waves","thermal")}; counts={s:sum(x.status==s for x in criteria) for s in ("validated","partial","negative","not_yet")}
    return {"valid":True,"criterion_count":len(criteria),"domain_counts":domains,"status_counts":counts,"documented_summary_total":DOCUMENTED_SUMMARY_TOTAL,"matrix_total_mismatch":DOCUMENTED_SUMMARY_TOTAL-len(criteria),"missing_explicit_criterion":MISSING_EXPLICIT_CRITERION}

def canonical_payload()->dict[str,Any]:return {"schema":"openwave.m9.models-conformance.v1","model":"M9 CAT/EPT","criteria":[asdict(x) for x in CRITERIA],"audit":validate_profile()}
def fingerprint()->str:return sha256(json.dumps(canonical_payload(),sort_keys=True,separators=(",",":")).encode()).hexdigest()
def run_conformance_study()->dict[str,Any]:
    payload=canonical_payload(); acceptance={"all_explicit_rows_covered":payload["audit"]["criterion_count"]==21,"domain_partition_closes":payload["audit"]["domain_counts"]=={"particles":12,"forces":5,"waves":3,"thermal":1},"nonplanned_cells_have_evidence":all(x["status"]=="not_yet" or bool(x["evidence"]) for x in payload["criteria"]),"honest_negative_preserved":sum(x["status"]=="negative" for x in payload["criteria"])==2,"summary_total_closes":payload["audit"]["matrix_total_mismatch"]==0,"thermal_criterion_is_explicit":any(x["key"]=="thermal_field" for x in payload["criteria"]),"deterministic_fingerprint":fingerprint()==fingerprint(),"m9_46_48_status_counts":payload["audit"]["status_counts"]=={"validated":0,"partial":19,"negative":2,"not_yet":0}}
    return {**payload,"fingerprint":fingerprint(),"acceptance":acceptance,"passed":all(acceptance.values()),"repository_profile":"MODELS_M9.md"}
def result_to_json(result:dict[str,Any])->str:return json.dumps(result,indent=2,sort_keys=True)+"\n"
