"""M14 CAT/EPT continuum AdS double-copy lineage."""
from .causal_green_hadamard_m141 import CausalGreenHadamardConfig, run_causal_green_hadamard_study
from .infinite_bcj_direct_limit_m142 import InfiniteBCJDirectLimitConfig, run_infinite_bcj_direct_limit_study
from .ads_normalized_continuum_double_copy_m143 import AdSNormalizedContinuumConfig, run_ads_normalized_continuum_double_copy_study
from .smooth_continuum_ads_double_copy_m144 import SmoothContinuumAdSDoubleCopyConfig, run_smooth_continuum_ads_double_copy_study
run_m14_model_study=run_smooth_continuum_ads_double_copy_study
__all__=["CausalGreenHadamardConfig","InfiniteBCJDirectLimitConfig","AdSNormalizedContinuumConfig","SmoothContinuumAdSDoubleCopyConfig","run_causal_green_hadamard_study","run_infinite_bcj_direct_limit_study","run_ads_normalized_continuum_double_copy_study","run_smooth_continuum_ads_double_copy_study","run_m14_model_study"]
