"""M13 CAT/EPT scale-dilation and holographic-amplitude model lineage."""
from .model_registration import ScaleDilationSolitonConfig, run_scale_dilation_soliton_study
from .holographic_bcj_twistor_wilson_m132 import HolographicAmplitudeConfig, run_holographic_amplitude_study
from .yukawa_dilation_gkp_m133 import YukawaDilationGKPConfig, run_yukawa_dilation_gkp_study
from .yukawa_rt_holographic_entropy_m134 import YukawaRTHolographicConfig, run_yukawa_rt_holographic_study
from .bcj_yukawa_holographic_synthesis_m135 import BCJYukawaHolographicConfig, run_bcj_yukawa_holographic_study
from .holographic_rg_cutoff_flow_m136 import HolographicRGConfig, run_holographic_rg_study
from .wilson_rt_surface_scaling_m137 import WilsonRTScalingConfig, run_wilson_rt_scaling_study
from .bcj_gkp_source_kernel_m138 import BCJGKPSourceKernelConfig, run_bcj_gkp_source_kernel_study
from .penrose_holographic_mass_entropy_m139 import PenroseHolographicConfig, run_penrose_holographic_study
from .lossless_holographic_reduction_m1310 import HolographicReductionConfig, run_holographic_reduction_study
run_m13_model_study=run_holographic_reduction_study
__all__=["ScaleDilationSolitonConfig","HolographicAmplitudeConfig","YukawaDilationGKPConfig","YukawaRTHolographicConfig","BCJYukawaHolographicConfig","HolographicRGConfig","WilsonRTScalingConfig","BCJGKPSourceKernelConfig","PenroseHolographicConfig","HolographicReductionConfig","run_scale_dilation_soliton_study","run_holographic_amplitude_study","run_yukawa_dilation_gkp_study","run_yukawa_rt_holographic_study","run_bcj_yukawa_holographic_study","run_holographic_rg_study","run_wilson_rt_scaling_study","run_bcj_gkp_source_kernel_study","run_penrose_holographic_study","run_holographic_reduction_study","run_m13_model_study"]
